### PR TITLE
Allow content to scroll

### PR DESCRIPTION
**Pull request by mmanela**
When I tested the plugin I was only able to see the top part of it in both chrome and firefox. I was not able to scroll to the rest.

The following changes attempt to fix that by allowing it to scroll.

### CODE REVIEW

**Comment by micmro** [comment]
Thanks a lot for the contribution. I have just a few questions:
I assume this bug happened on a site that hides the vertical overflow? Making it scrollable will probably cause issues with regular pages, did you test if that worked?
If not can you give me a few example URL that failed so I can test it as well?

**Comment by mmanela** [comment]
I noticed the issue jsfiddle.net. I did test on other scrollable sites and it works ok. This plugin just becomes a 100% scrollable pane

**Comment by micmro** [comment]
I finally got around to build your branch and test it. It looks good, the only concern I have (sorry to be nit-picky) is that it won't allow you on regular (non `overflow:hidden`) pages to take a full length screenshot. I think this could be solved in code though: if `overflow:hidden` is set on the `body` use your style else use the existing one.
Unfortunately I probably won't have time to look into this until the weekend, but would be happy if you can give it a stab.

**Comment by micmro** [comment]
Merged with PR #30

**Comment by mmanela** [comment]
Thanks!

**Pull request closed without merging**
